"""
Google Credentials Setup Script for TailorTalk Enhanced
Helps users configure Google Cloud credentials for OAuth2 authentication
"""
import os
import json
import logging
from pathlib import Path
from typing import Dict, Any

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def create_directories():
    """Create necessary directories"""
    directories = ['config', 'auth_data', 'logs']
    
    for directory in directories:
        Path(directory).mkdir(exist_ok=True)
        logger.info(f"✅ Directory created/verified: {directory}")

def validate_credentials_file(credentials_path: str) -> bool:
    """Validate Google credentials file"""
    try:
        if not os.path.exists(credentials_path):
            logger.error(f"❌ Credentials file not found: {credentials_path}")
            return False
        
        with open(credentials_path, 'r') as f:
            credentials = json.load(f)
        
        # Check required fields
        required_fields = ['client_id', 'client_secret', 'auth_uri', 'token_uri']
        
        if 'web' in credentials:
            creds_data = credentials['web']
        elif 'installed' in credentials:
            creds_data = credentials['installed']
        else:
            logger.error("❌ Invalid credentials format")
            return False
        
        missing_fields = [field for field in required_fields if field not in creds_data]
        
        if missing_fields:
            logger.error(f"❌ Missing required fields: {missing_fields}")
            return False
        
        logger.info("✅ Credentials file is valid")
        return True
        
    except json.JSONDecodeError:
        logger.error("❌ Invalid JSON in credentials file")
        return False
    except Exception as e:
        logger.error(f"❌ Error validating credentials: {e}")
        return False

def setup_environment_variables():
    """Setup environment variables"""
    env_vars = {
        'GOOGLE_CREDENTIALS_PATH': 'config/credentials.json',
        'ENCRYPTION_PASSWORD': 'tailortalk-secure-key-2024',
        'HOST': 'localhost',
        'PORT': '8001',
        'DEBUG': 'false'
    }
    
    env_file = Path('.env')
    
    # Read existing .env file if it exists
    existing_vars = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.strip().startswith('#'):
                    key, value = line.strip().split('=', 1)
                    existing_vars[key] = value
    
    # Update with new variables
    existing_vars.update(env_vars)
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# TailorTalk Enhanced Environment Variables\n")
        f.write("# Generated by setup_google_credentials.py\n\n")
        
        for key, value in existing_vars.items():
            f.write(f"{key}={value}\n")
    
    logger.info("✅ Environment variables configured in .env file")

def create_sample_credentials():
    """Create a sample credentials file for reference"""
    sample_credentials = {
        "web": {
            "client_id": "YOUR_CLIENT_ID.apps.googleusercontent.com",
            "project_id": "your-project-id",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": "YOUR_CLIENT_SECRET",
            "redirect_uris": [
                "http://localhost:8001/auth/callback"
            ]
        }
    }
    
    sample_path = Path('config/credentials_sample.json')
    
    with open(sample_path, 'w') as f:
        json.dump(sample_credentials, f, indent=2)
    
    logger.info(f"✅ Sample credentials file created: {sample_path}")

def print_setup_instructions():
    """Print detailed setup instructions"""
    instructions = """
🔧 GOOGLE CLOUD SETUP INSTRUCTIONS
==================================

1. CREATE GOOGLE CLOUD PROJECT
   • Go to: https://console.cloud.google.com/
   • Create a new project or select existing one
   • Note your project ID

2. ENABLE GOOGLE CALENDAR API
   • Go to: APIs & Services > Library
   • Search for "Google Calendar API"
   • Click "Enable"

3. CONFIGURE OAUTH CONSENT SCREEN
   • Go to: APIs & Services > OAuth consent screen
   • Choose "External" user type
   • Fill in required information:
     - App name: TailorTalk Enhanced
     - User support email: your-email@example.com
     - Developer contact: your-email@example.com
   • Add scopes:
     - https://www.googleapis.com/auth/calendar
     - https://www.googleapis.com/auth/userinfo.email
     - https://www.googleapis.com/auth/userinfo.profile
   • Add test users (your email addresses)

4. CREATE OAUTH2 CREDENTIALS
   • Go to: APIs & Services > Credentials
   • Click "Create Credentials" > "OAuth 2.0 Client IDs"
   • Application type: "Web application"
   • Name: "TailorTalk Enhanced"
   • Authorized redirect URIs:
     - http://localhost:8001/auth/callback
     - http://127.0.0.1:8001/auth/callback
   • Click "Create"

5. DOWNLOAD CREDENTIALS
   • Click the download button for your OAuth 2.0 Client
   • Save as: config/credentials.json
   • DO NOT commit this file to version control!

6. TEST SETUP
   • Run: python config/setup_google_credentials.py
   • Start the application: python main1.py
   • Visit: http://localhost:8001
   • Test authentication flow

📋 IMPORTANT NOTES
==================
• Keep credentials.json secure and private
• Add config/credentials.json to .gitignore
• For production, use environment variables
• Test users must be added in OAuth consent screen
• Quota limits apply - monitor usage in Google Cloud Console

🔗 HELPFUL LINKS
=================
• Google Cloud Console: https://console.cloud.google.com/
• Calendar API Docs: https://developers.google.com/calendar/api
• OAuth2 Guide: https://developers.google.com/identity/protocols/oauth2
• Scopes Reference: https://developers.google.com/identity/protocols/oauth2/scopes

"""
    
    print(instructions)

def main():
    """Main setup function"""
    print("🚀 TailorTalk Enhanced - Google Credentials Setup")
    print("=" * 50)
    
    # Create directories
    create_directories()
    
    # Setup environment variables
    setup_environment_variables()
    
    # Create sample credentials file
    create_sample_credentials()
    
    # Check if credentials file exists
    credentials_path = 'config/credentials.json'
    
    if os.path.exists(credentials_path):
        print(f"\n📁 Found credentials file: {credentials_path}")
        
        if validate_credentials_file(credentials_path):
            print("✅ Setup completed successfully!")
            print("\n🎯 Next steps:")
            print("1. Start the FastAPI server: python main1.py")
            print("2. Start the Streamlit app: streamlit run enhanced_streamlit_app.py")
            print("3. Visit: http://localhost:8501")
        else:
            print("❌ Credentials file is invalid. Please check the format.")
            print_setup_instructions()
    else:
        print(f"\n⚠️  Credentials file not found: {credentials_path}")
        print("Please follow the setup instructions below:")
        print_setup_instructions()
    
    print("\n" + "=" * 50)
    print("Setup script completed!")

if __name__ == "__main__":
    main()
